services:
  whatsapp:
    build: ./whatsapp
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080" ]
    ports:
      - "8080:8080"
    depends_on:
      - rocketchat
      - mongodb
      - rocket_chat_omnichannel